name: "Docker Stack Deploy Swarm Action"
description: "Deploy a Docker Stack"
author: "Vrashabh-Sontakke"
branding:
  icon: "layers"
  color: "green"

inputs:
  host:
    description: "Docker Host"
    required: true
  port:
    description: "Docker Port"
    default: "22"
    required: false
  user:
    description: "Docker User"
    required: true
  pass:
    description: "Docker Pass"
    required: false
  ssh_key:
    description: "SSH Key File"
    required: false
  file:
    description: "Docker Compose File"
    default: "docker-compose.yaml"
    required: false
  name:
    description: "Docker Stack Name"
    required: true
  env_file:
    description: "Environment File"
    required: false
  private_registry:
    description: "Add --with-registry-auth flag to docker stack deploy"
    required: false
    default: "false"
  args:
    description: "Additional arguments to pass to docker stack deploy command"
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
